### PR TITLE
Demonstrations abstraction

### PR DESCRIPTION
**Pull request by parthasarathydNU**
# Enhancements to Demonstration Components for Improved Reusability and Simplification

### Summary 

This PR introduces some changes to our component composing for the sample pages, focusing on enhancing reusability and simplification for developers. By abstracting the demonstration components into a more generic form and allowing component-specific data to be defined in JSON format, we've streamlined the process of adding new component demonstrations. This update aims to make it easier for developers to showcase new components and features with minimal overhead.

### Key Changes

**Abstracting Demonstration Components:** We've refactored the demonstration components to accept data through props, making them agnostic of the specific content they display. This abstraction allows us to reuse these components across various parts of our application, significantly reducing code duplication.

**JSON Data for Components:** Developers can now define the data for each component's demonstrations in a separate JSON file. This approach separates the data layer from the presentation layer, making it easier to manage and update component demonstrations.

**Usage Examples:** To assist developers in adopting these changes, ive've included detailed usage examples. These examples illustrate how to define demonstration data in JSON and how to pass this data to the abstracted demonstration components.

### Usage Examples

Defining Component Data in JSON
Create a vue file (e.g., avatarData.json) with the following structure:

```vue
// data/avatarData.vue
<script>
export default {
  data: [
    {
      title: "Standard Avatar",
      previewCode: `<div class="avatar">
              <div class="w-24 rounded">
              <img src="https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg" />
              </div>
          </div>`,
    },
   //  ... data for other components here
</script>
```

### Using Abstracted Demonstration Component (DemonstrationComposer.vue)

```vue
// avatar.vue
<template>
  <DemonstrationComposer :demonstrations="avatarData" />
</template>

<script>
import AvatarData from "../../data/avatarData.vue";

export default {
  name: "Avatar",
  data() {
    return {
      avatarData: AvatarData.data
    };
  }
};
</script>
```

### Benefits

- **Improved Reusability:** Developers can now reuse the same demonstration components across different parts of the application, fostering a DRY (Don't Repeat Yourself) codebase.
- **Ease of Maintenance:** Separating the component data into JSON files allows for easier updates and maintenance without touching the Vue component files.
- **Enhanced Flexibility:** This approach provides developers with the flexibility to add or update component demonstrations by merely updating the JSON files, streamlining the workflow for showcasing new features or components.

### Request for Feedback

We welcome feedback on the following aspects:
- Suggestions for further improving the reusability and flexibility of demonstration components.
- Ideas for additional data that could be included in the JSON files to enhance the demonstrations.
- Feedback on the clarity and usefulness of the provided usage examples.

### CODE REVIEW

**Comment by amandesai01** [comment]
Already went through this approach. Problem is, in many cases, we want different output code and code used to render output.
Example, we want to center the button while displaying / put them in flex, etc. which is not possible with this.
So, one approach is, we can keep both the components, and while implementing, we can decide which one to use.

We cannot proceed with this currently due to minumum bandwidth and changes happening too frequently that it would be difficult to propagate changes to everyone. But we will surely circle back once all pages are done.

Feel free to file an open issue to discuss further.

IMP NOTE: Please open an issue and get an approval first before investing your valuable time to avoid such cases in future.

**Comment by parthasarathydNU** [comment]
I understand Amans point, but I think this way we can easily make the styling and layout consistent  across all pages and just focus on getting the data in. Yet to see where this will be inconvenient.

**Comment by parthasarathydNU** [comment]
For the current task as long as we want all components to be aligned the same way across all pages we can use this, only for specific pages where we are seeking deviation we can manually create the html. which would be in lesser numbers i think

**Comment by amandesai01** [comment]
Understood and appreciated, closing this PR for now, I will revisit at this approach later.

**Pull request closed without merging**
